//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class datas
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string phonenumber { get; set; }
        public string mail { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    }
}
